title: ポートフォリオ
description: NIRANKEN
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

# GitHub metadata
repository: NIRANKEN/niranken-profile.github.io
github:
  is_project_page: false
